name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Build Docker image
        run: docker build -t mymodelapi:latest ./app

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" | docker login <your-registry-name>.azurecr.io -u <your-registry-username> --password-stdin

      - name: Push Docker image to Azure Container Registry
        run: docker push <your-registry-name>.azurecr.io/mymodelapi:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-app-name>
          slot-name: production
          images: <your-registry-name>.azurecr.io/mymodelapi:latest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
